apiVersion: v1
kind: Secret
metadata:
  name: aegisops-secrets
  namespace: aegisops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root_secure_pass_2026"
  MYSQL_PASSWORD: "emergency_secure_pass_2026"
  MYSQL_USER: "emergency_user"
  JWT_SECRET: "aegisops-super-secure-production-jwt-key-2026-spring-edition-minimum-32-chars"
